
## 首页
home: true
logoColor: '#2c3e50'
showFont: 程
faviconIco: https://ooszy.cco.vin/img/blog-public/ccds_64.ico
customRandomSay: false
customRandomValue: 青衫烟雨客
showHomeMood: false
heroLogo: https://ooszy.cco.vin/img/blog-public/avatar.jpg
logo: https://ooszy.cco.vin/img/blog-public/head.jpg
cancelIcoHref: https://ooszy.cco.vin/img/ico/quxiao.svg
logoTitle: qsyyke
description: qsyyke的个人博客，记录生活琐事，学习笔记
keyword: vuepress主题,vuepress theme,生活琐事,二次元博客,简约博客,博客主题,静态主题
socialMaxLength: 7
slideTime: 3000
#随机一言接口
randomSaw: https://international.v1.hitokoto.cn/?c=b&max_length=45
#拿取对象
randomSawQuery: hitokoto
method: get
animeOption: {
  baseURL: https://api.vvhan.com/api/acgimg?type=json,
  method: get,
  timeout: 5000,
  query: imgurl
}
heroImage: "https://ooszy.cco.vin/img/blog-public/head.jpg"
#首页中间框的话语
mood: 青衫烟雨客
isFitter: true






## 文章页面
lazyLoadingImg: https://ooszy.cco.vin/img/blog-public/ljz.gif
#默认文章页，标题颜色
defaultTitleColor: #8093f1


## 社交
socials: [
  {
    aHref: mailto:2291308094@qq.com,
    imgSrc: https://ooszy.cco.vin/img/ico/email.svg,
    isHome: false,
    show: false
  }
]

#关于页面
about: [
  {
    bar: false,
    title: '我?',
    describe: [],
    tag: [],
    showTag: true
  },
  {
    bar: false,
    title: '大三规划',
    describe: [],
    tag: [],
    showTag: true
  },
  {
    bar: false,
    title: '未来规划',
    describe: [],
    tag: [

    ],
    showTag: false
  },
  {
    bar: true,
    title: '技  能',
    describe: [
      {
        name: 'springBoot',
        score: 82
      },
    ],
    showTag: false
  },

  {
    showTag: false,
    bar: true,
    title: '掌握框架',
    describe: [
      {
        name: 'dubbo',
        score: 61
      },

    ]
  },
  {
    bar: true,
    showTag: false,
    title: '掌握技能',
    describe: [
      {
        name: 'Ctrl C V',
        score: 100
      }

    ]
  },
  {
    title: '关于主题',
    describe: [
        该主题是我自己独立开发，是一款基于vuepress，对默认主题进行了大量修改，我以前使用的是博客主题，但是我对PHP不了解，想改成自己想要的主题，太难了，最近在学vue，正好看到可以使用vuepress来搭建 博客，就将默认主题改成现在这个样，并且喜欢vuepress的最主要原因是，它可以 直接将本地的markdown文档进行编译部署，我原来博客，我记了几个月的笔记，不太想再慢慢从本地复制到WordPress进行发布，以至于博客几个月没有发布文章了，虽然有技术可以解决，但是 还是喜欢vuepress，简直是懒癌福音，如果你喜欢的话，可以 在我的GitHub进行下载，使用文档我还没有写，该主题已将所有的配置进行抽离，你现在看到的所有信息，都抽离在了一个配置文件中，可以做到开箱即用，并且我自己也写了几个组件，包括文章页面看到的顶部图片，友情链接等等 ，可以在你想使用的地方，直接使用这些组件就可以，该主题我加入了vuex，对前端不太了解，有很多css不对的地方，请大家多多包涵，Thanks♪(･ω･)ﾉ
    ]
  },
  {
    bar: false,
    title: '更新日志',
    describe: [
        '更新日志',
        '更新日志',
        '更新日志',
        '更新日志',
        '项目'
    ],
    tag: [

    ],
    showTag: false
  },
]


#随机图片地址，设置背景用
randomWallpaper: https://api.iro.tw/webp_pc.php
randomWallpaperMb: https://api.iro.tw/webp_mb.php

##颜色及字体
#这是配置随机背景；颜色
randomColor: ['#ffcad4']
maxFontColorArr: 8
fontColor: ['#2c3e50']
fontFamily: ["-apple-system"]

## 友情链接
friendLinks: [
  {
    title: 另一博客,
    url: https://cco.vin/,
    logo: https://vipblogs.cn/wp-content/uploads/2021/03/bitbug_favicon.ico,
    describe: 以前博客
  },
]
#自己的站点信息 我自己的站点描述
siteInformation: {
  title: 青衫烟雨客,
  url: https://vipblogs.cn,
  logo: https://ooszy.cco.vin/img/blog-public/1.png,
  describe: 这是我的站点描述
}
ico: {
  linkIco: https://ooszy.cco.vin/img/ico/tea.svg,
  aboutIco: https://ooszy.cco.vin/img/ico/cat.svg,
  homeWelcome: [
      http://ooszy.cco.vin/img/ico/love2.svg,
      http://ooszy.cco.vin/img/ico/xy.svg,
  ]
}

## 标签
#需要排除的标签，自动生成的标签中，不会有这个标签
excludeTag:
  - note

## 页脚
footer:
  - Copyright © by qsyyke All Rights Reserved.
  - Theme <a href="https://www.cco.vin">ccds</a> by qsyyke
  - "<a target='_blank' href='http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=53060202000142' style='display:inline-block;text-decoration:none;height:20px;line-height:20px;'><img src='' style='float:left;'/><p style='float:left;height:20px;line-height:20px;margin: 0px 0px 0px 5px;'>滇公网安备 53060202000142号</p></a>"
isShowFooter: true
#是否展示运行时间
isShowRunTime: true
startRunTime: 8/7/2021 12:22:00
prefixRuntime: 小破站已运行
#如果没有设置key值，那么就截取描述作为key，keyRule就是截取多少个字
keyRule: 40

#通知
message: 目前博客还没开发评论，如需添加友情链接，请到我旧博客添加评论评论我都会看，看到会添加到此处<a target="_blank" href="https://www.cco.vin/%e5%8f%8b%e6%83%85%e9%93%be%e6%8e%a5/">点击进入</a>
isShowMessage: true

adsenseArr: [
  {
    position: center,
    adsenseMessage: 官网用户专享3,
    script: <a href="https://baidu.com">这是中间3</a>,
    adsenseBackgroundImg: /img/33.jpg,
  },
]
insertAdsenseRule: 17
#每一页文章中，最大广告数
adsenseLength: 3
recommendPageLength: 30
#推荐列表标题为空时，就会使用这个进行代替，默认是`╮(￣▽￣)╭`
recommendNoTitle: '`╮(￣▽￣)╭`'
#tag页，没有标题时，代替文字 默认是下面这个
tagNoTitle: 暂时还没有标题哟

split: "~"
donate: {
  donateImg: [
      https://ooszy.cco.vin/img/blog-public/wxpay.png,
      https://ooszy.cco.vin/img/blog-public/zfbpay.jpg
  ],
  articlePage: true,
  aboutPage: true,
  donateProduct: [
    {
      name: 奶茶,
      img: https://ooszy.cco.vin/img/blog-public/nc.jpeg,
      price: 18,
      prefix: $
    }
  ],
  onlineList: true,
  donateList: [
    {
      name: 初尘,
      msg: 主题太棒了,
      img: https://ooszy.cco.vin/img/blog-public/nc.jpeg,
      price: 7,
      prefix: ￥
    },
  ],
}

#评论配置
comment: {
  showComment: true,
  #占位符
  placeholder: 在这里留下你的脚印吧...,
  appId: LwdW7EDeTGFUjTfUToF9WjEh-gzGzoHsz,
  appKey: yGiWpb4TbwSz5ihpfloV1gDX,
  #头像显示
  avatar: robohash,
  # 每页评论数量
  pageSize: 3,
  #是否开启访问量
  visitor: true,
  # 是否记录评论者ip
  recordIP: true,
  # 是否自动获取用户qq头像，需根据qq号码
  adminUsername: qsyyke
}

## 海报
poster: {
  description: 初尘博客呀,
  author: 'qsyyke',
  preBlog: 'chuchen',
  suffixBlog: 'blog',
  avatar: /avatar.png
}